POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "tom",
  "email": "tomdu3@ymail.com",
  "password": "password1!"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "mick",
  "email": "mick@gmail.com",
  "password": "12Removal{}"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "tom@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mick@gmail.com",
  "password": "12Removal{}"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "tom",
  "password": "password1!" 
}

###

POST http://localhost:3000/api/auth/logout
Content-Type: application/json


###

GET http://localhost:3000/api/test


###
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

### User Routes
# Get current user profile
GET http://localhost:3000/api/users/profile

### Update user profile
PUT http://localhost:3000/api/users/profile
Content-Type: application/json

{
  "email": "tomdu3@ymail.com",
  "currentPassword": "pas1sword!!",
  "newPassword": "password1!",
  "preferences": {
    "seat": "window",
    "meal": "breakfast",
    "newsletter": true
  }
}