POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "tom",
  "email": "tom@gmail.com",
  "password": "123to?x"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "mick",
  "email": "mick@gmail.com",
  "password": "12Removal{}"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "tom@gmail.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "tom",
  "password": "pas1sword!" 
}

###

POST http://localhost:3000/api/auth/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjUyM2NkNmNlMjYwOTlkNjgzNDQzZCIsImlhdCI6MTc0NDI3OTkwNiwiZXhwIjoxNzQ0MjgwODA2fQ.MrkYSuF_Cluyr95VvPvD-MknvdclrXHlzufh_95bI88"
}

###

GET http://localhost:3000/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjUyM2NkNmNlMjYwOTlkNjgzNDQzZCIsImlhdCI6MTc0NDI4MDExMSwiZXhwIjoxNzQ0MjgwMTI2fQ.wM0GpGPGhsbtk8ttHE7dgkB8dN4pxuvYWutfnF81J14