POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "tom",
  "email": "tom@gmail.com",
  "password": "123to?x"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "mick",
  "email": "mick@gmail.com",
  "password": "12Removal{}"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "tom@gmail.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "tom",
  "password": "pas1sword!" 
}

###

POST http://localhost:3000/api/auth/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjU1ZDY0YTY4YTk1YWVlMDY3YjM5YiIsImlhdCI6MTc0NDEzMzQ3NywiZXhwIjoxNzQ0MTM3MDc3fQ.OTxu2dWNDO8QB0Ayosmr8lx7hWripAFGJZydUUnkvXA"
}

###

GET http://localhost:3000/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjUyM2NkNmNlMjYwOTlkNjgzNDQzZCIsImlhdCI6MTc0NDIxNTE5OSwiZXhwIjoxNzQ0MjE4Nzk5fQ._zbbns5uLDYPLKQDC9CUPxgNrkGvv3W3TcWfBVt4lWE